spring.application.name=gameLib
server.port=8087

spring.data.mongodb.uri=mongodb://root:secret@localhost:27017/mydatabase
spring.data.mongodb.database=mydatabase

steam.api_url="api.steampowered.com"
steam.api_key="cjdewflfjknrlfew"
