spring.application.name=gameLib
server.port=8087
spring.mongodb.uri=mongodb://mongo:cJWloUvMOpyycLQLOnzjmoBtIJQVLVCt@caboose.proxy.rlwy.net:10402/steamDB?authSource=admin

# Springdoc OpenAPI Configuration (for springdoc 3.x)
springdoc.swagger-ui.tryItOutEnabled=true

jwt.secret= NtXGuIQ55FH0yXWqcHkdXQ91m3ai1WCT2cvwjpFlp/cl8Gkjbv4S+UdAuk1BHJu5RRoNu15j09CICW51jbVK6A==
jwt.expiration-time= 86400000

config.redirect-uri= "http://localhost:3000"



spring.security.oauth2.client.registration.google.client-id=68203913645-ono46vmfmupihbk4fq5cdmk15l58gdut.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=68203913645-ono46vmfmupihbk4fq5cdmk15l58gdut.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.scope=openid,profile,email
